routes:
  /:
    uses: index
    as: aardvark-seo
  general:
    uses: getGeneralForm
    as: aardvark-seo.general
  defaults:
    uses: DefaultsController@index
    as: aardvark-seo.defaults
  defaults/{content}/{slug}:
    uses: DefaultsController@single
    as: aardvark-seo.defaults.single
  post@defaults/{content}/{slug}:
    uses: DefaultsController@save
    as: aardvark-seo.defaults.save
  marketing:
    uses: getMarketingForm
    as: aardvark-seo.marketing
  social:
    uses: getSocialForm
    as: aardvark-seo.social
  post@update:
    uses: cpUpdate
    as: aardvark-seo.update-globals
  redirects:
    uses: RedirectsController@index
    as: aardvark-seo.redirects
  post@updateRedirects:
    uses: RedirectsController@cpUpdate
    as: aardvark-seo.update-redirects
  sitemap:
    uses: SitemapController@index
    as: aardvark-seo.sitemap
  post@updateSitemap:
    uses: SitemapController@cpUpdate
    as: aardvark-seo.update-sitemap
  aardvark-seo-json:
    uses: AardvarkSeoJsonController@index
    as: aardvark-seo.aardvark-seo-json
